pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                git branch: 'jenkins', url: 'https://github.com/gokulprasadtr/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('build and test') {
            steps {
                sh 'ls -ltr'
            }
        }
    }
}
