pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    stages {
        stage('checkout') {
            steps {
                git branch: 'jenkins', url: 'https://github.com/gokulprasadtr/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('build and test') {
            steps {
                sh 'ls -ltr'
                sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
            }
        }
    }
}
