pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    environment {
        SONAR_URL = 'http://sonarqube:9000'
    }

    stages {
        stage('checkout') {
            steps {
                git branch: 'jenkins', url: 'https://github.com/gokulprasadtr/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('build and test') {
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app')
                sh 'mvn clean package'
            }
        }
        stage('Sonarqube analysis') {
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    withSonarQubeEnv('SonarQube-Server') {
                        sh '''
                          mvn sonar:sonar \
                            -Dsonar.projectKey=my-java-app-key \
                            -Dsonar.projectName="My Java Application" \
                            -Dsonar.java.binaries=target/classes
                        '''
                    }
                }
            }
        }
    }
}